link_with 'Ignite', 'IgniteTests'
use_frameworks!

pod 'SwiftyJSON'
pod 'Alamofire'
pod 'Locksmith'
pod 'Timepiece'
pod 'DZNEmptyDataSet'
pod 'Parse'
pod 'Fabric'
pod 'Crashlytics'
pod 'CVCalendar'
pod 'Charts'
pod 'ChameleonFramework/Swift'
pod 'DKChainableAnimationKit'
pod 'JSQMessagesViewController'
pod 'TextFieldEffects'
pod 'LTMorphingLabel'
